### ISSUE TITLE
transformerClass ClassNotFoundException

### ISSUE THREAD

**Issue by fraadsbrandth** [hielkehoeve/maven-javassist#4]
Hi!

I can't get this plugin to work properly.
Does not find my defined transformer class.
Any idea why this is not working?

I have set this as a dependency

``` java
<dependency>
    <groupId>nl.topicus.plugins</groupId>
    <artifactId>javassist-maven-plugin-core</artifactId>
    <version>2.1</version>
    <scope>provided</scope>
</dependency>
```

And setup the plugin like this

``` java
<plugin>
    <groupId>nl.topicus.plugins</groupId>
    <artifactId>javassist-maven-plugin</artifactId>
    <version>2.1</version>
    <configuration>
        <transformerClass>com.myexample.ResourceTransformer</transformerClass>
        <processInclusions>
            <inclusion>com.myexample.transform</inclusion>
        </processInclusions>
    </configuration>
    <executions>
        <execution>
            <phase>process-classes</phase>
            <goals>
                <goal>javassist</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

This is the exception I'm getting

``` java
[ERROR] Failed to execute goal nl.topicus.plugins:javassist-maven-plugin:2.1:javassist (default) on project my-project: com.myexample.ResourceTransformer -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal nl.topicus.plugins:javassist-maven-plugin:2.1:javassist (default) on project my-project: com.myexample.ResourceTransformer
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: com.myexample.ResourceTransformer
        at nl.topicus.plugins.maven.javassist.JavassistMojo.instantiateTransformerClass(JavassistMojo.java:178)
        at nl.topicus.plugins.maven.javassist.JavassistMojo.transform(JavassistMojo.java:81)
        at nl.topicus.plugins.maven.javassist.JavassistMojo.execute(JavassistMojo.java:67)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.lang.ClassNotFoundException: com.myexample.ResourceTransformer
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:789)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:270)
        at nl.topicus.plugins.maven.javassist.JavassistMojo.instantiateTransformerClass(JavassistMojo.java:175)
        ... 23 more
```

**Comment by stelcheck** [comment]
I am also getting this issue with version 2.2 of the code.

**Comment by vroyer** [comment]
I had the same issue, fixed by modifying the following code in JavassistMojo.java 

```
private List<String> getCompileClasspathElements() 
        throws DependencyResolutionRequiredException {
		List<?> ret = project.getCompileClasspathElements();
		info("Scan project.build.outputDirectory="+project.getBuild().getOutputDirectory());
		return Lists.newArrayList(project.getBuild().getOutputDirectory());
}
```

**Comment by SaltOfTheFlame** [comment]
waiting for this fix

**Comment by hielkehoeve** [comment]
A "little" late but you need to following setup. The README was incomplete:

- **Project A**, containing the classes you wish to process

- **Project A-transformer**, containing only the transformer class (you don't want this to end up in either A or A-android)
`src/main/java/nl/topicus/hello/transformer/AndroidTransformer.java`

```<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>nl.topicus.hello</groupId>
	<artifactId>A-transformer</artifactId>
	<version>1.0-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>A Android Transformer</name>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>nl.topicus.plugins</groupId>
				<artifactId>javassist-maven-plugin-core</artifactId>
				<version>2.1</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>nl.topicus.plugins</groupId>
			<artifactId>javassist-maven-plugin-core</artifactId>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>
```


- **Project A-android**, containing nothing except a pom.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>nl.topicus.hello</groupId>
	<artifactId>A-android</artifactId>
	<version>1.0-SNAPSHOT</version>
	<packaging>jar</packaging>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>nl.topicus.hello</groupId>
				<artifactId>A</artifactId>
				<version>${project.version}</version>
				<!-- set this to provided to make sure it won't be included in any android project -->
				<scope>provided</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>nl.topicus.hello</groupId>
			<artifactId>A</artifactId>
		</dependency>
	</dependencies>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>nl.topicus.plugins</groupId>
					<artifactId>javassist-maven-plugin</artifactId>
					<version>2.1</version>
					<dependencies>
						<dependency>
							<groupId>nl.topicus.hello</groupId>
							<artifactId>A-transformer</artifactId>
							<version>1.0-SNAPSHOT</version>
						</dependency>
					</dependencies>
					<configuration>
<transformerClass>nl.topicus.hello.AndroidTransformer</transformerClass>
						<processInclusions>
							<inclusion>nl.topicus.hello</inclusion>
						</processInclusions>
						<processExclusions>
							<exclusion>nl.topicus.cobra.hello.exception</exclusion>
						</processExclusions>
						<exclusions>
							<exclusion>javax</exclusion>
						</exclusions>
					</configuration>
					<executions>
						<execution>
							<phase>process-classes</phase>
							<goals>
								<goal>javassist</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
			</plugins>
		</pluginManagement>

		<plugins>
			<plugin>
				<groupId>nl.topicus.plugins</groupId>
				<artifactId>javassist-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>

```
